### ISSUE TITLE
Enhancement: Add fall through / wildcard for metadataconfig.yaml

### ISSUE THREAD

**Issue by ryan-dyer** [almariah/k8s-metadata-injector#4]
It would be really great if one didnt have to add a new entry into the configmap/yaml file every time a new namespace is added to the cluster.  We have a collection of tags we want added to every service and ebs by default cluster wide. 

ie something like:
```
    service:
      default:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "foo=bar"
      *:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "dog=canine"
```

**Comment by almariah** [comment]
@ryan-dyer Do you mean adding the ability to have default metadata-injection if namespace is not specified?

**Comment by ryan-dyer** [comment]
Sorry for delay in response.  Yes looking for a way to have a default set of tags applied to the resources in a namespace if that namespace isnt not specifically listed in the config file.

**Comment by almariah** [comment]
https://github.com/almariah/k8s-metadata-injector/pull/6

**Comment by almariah** [comment]
https://github.com/almariah/k8s-metadata-injector/pull/6
